// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: juVZkpy6GyNsQ7cQcnMtYR
// Component: NjqIRJcP1PtR
import * as React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import {
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  hasVariant
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import Header from "../../Header"; // plasmic-import: o3OmhqmRx_2W/component
import PersonCard from "../../PersonCard"; // plasmic-import: ItKVUfSkOclq/component
import ServiceValue from "../../ServiceValue"; // plasmic-import: 0YsWAKzXDvYV/component
import HomeFooterTop from "../../HomeFooterTop"; // plasmic-import: hl1a0oV_dA0U/component
import FooterMain from "../../FooterMain"; // plasmic-import: tesvkPR1z3Cj/component
import { useScreenVariants as useScreenVariantsraGy9YoyxeH2 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: RaGy9YoyxeH2/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: juVZkpy6GyNsQ7cQcnMtYR/projectcss
import sty from "./PlasmicAboutUs.module.css"; // plasmic-import: NjqIRJcP1PtR/css

createPlasmicElementProxy;

export const PlasmicAboutUs__VariantProps = new Array();

export const PlasmicAboutUs__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicAboutUs__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsraGy9YoyxeH2()
  });
  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicAboutUs.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicAboutUs.pageMetadata.title}
        />

        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicAboutUs.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Stack__
            as={"div"}
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            hasGap={true}
            className={classNames(projectcss.all, sty.header)}
          >
            <Header
              className={classNames("__wab_instance", sty.header__gInan)}
            />
          </Stack__>
          <div
            data-plasmic-name={"aboutUsBanner"}
            data-plasmic-override={overrides.aboutUsBanner}
            className={classNames(projectcss.all, sty.aboutUsBanner)}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"foreground2"}
              data-plasmic-override={overrides.foreground2}
              hasGap={true}
              className={classNames(projectcss.all, sty.foreground2)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__bAhwM)}
              >
                <h1
                  data-plasmic-name={"h1"}
                  data-plasmic-override={overrides.h1}
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1
                  )}
                >
                  {hasVariant(globalVariants, "screen", "mobile")
                    ? "About US"
                    : "About Us"}
                </h1>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xti0X
                  )}
                >
                  {hasVariant(globalVariants, "screen", "mobile")
                    ? "Lorem Ipsum is simply dummy text of the printing and typesetting industry."
                    : "Lorem Ipsum is simply dummy text of the printing and typesetting industry."}
                </div>
              </Stack__>
            </Stack__>
          </div>
          <div
            data-plasmic-name={"ourTeamSection"}
            data-plasmic-override={overrides.ourTeamSection}
            className={classNames(projectcss.all, sty.ourTeamSection)}
          >
            <div
              data-plasmic-name={"columns"}
              data-plasmic-override={overrides.columns}
              className={classNames(projectcss.all, sty.columns)}
            >
              <div className={classNames(projectcss.all, sty.column__lxUey)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__lGvru
                  )}
                >
                  {"Our team"}
                </h2>
                <div
                  data-plasmic-name={"container"}
                  data-plasmic-override={overrides.container}
                  className={classNames(projectcss.all, sty.container)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"row1"}
                    data-plasmic-override={overrides.row1}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.row1)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column___9XWcW)}
                    >
                      <PersonCard
                        className={classNames(
                          "__wab_instance",
                          sty.personCard__kA8Gm
                        )}
                        image={{
                          src: "/plasmic/agency_website/images/team4Jpg.jpg",
                          fullWidth: 370,
                          fullHeight: 450,
                          aspectRatio: undefined
                        }}
                        slot={"Job title"}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__q59E1
                          )}
                        >
                          {"Lorem Ipsum"}
                        </h3>
                      </PersonCard>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__sNBgh)}
                    >
                      <PersonCard
                        className={classNames(
                          "__wab_instance",
                          sty.personCard__fsaiM
                        )}
                        image={{
                          src: "/plasmic/agency_website/images/tm1Jpg.jpg",
                          fullWidth: 400,
                          fullHeight: 400,
                          aspectRatio: undefined
                        }}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__vE0Ds
                          )}
                        >
                          {"Lorem Ipsum"}
                        </h3>
                      </PersonCard>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__wvX1)}
                    >
                      <PersonCard
                        className={classNames(
                          "__wab_instance",
                          sty.personCard__f7FxG
                        )}
                        image={{
                          src: "/plasmic/agency_website/images/team2Jpg3.jpg",
                          fullWidth: 370,
                          fullHeight: 450,
                          aspectRatio: undefined
                        }}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__x2UGy
                          )}
                        >
                          {"Lorem Ipsum"}
                        </h3>
                      </PersonCard>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__ufKel)}
                    >
                      <PersonCard
                        className={classNames(
                          "__wab_instance",
                          sty.personCard__f7Xv
                        )}
                        image={{
                          src: "/plasmic/agency_website/images/images1Jpg.jpg",
                          fullWidth: 225,
                          fullHeight: 225,
                          aspectRatio: undefined
                        }}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__q2JCf
                          )}
                        >
                          {"Lorem Ipsum"}
                        </h3>
                      </PersonCard>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__pEnbU)}
                    >
                      <PersonCard
                        className={classNames(
                          "__wab_instance",
                          sty.personCard__h4VNs
                        )}
                        image={{
                          src: "/plasmic/agency_website/images/avatar3Png.png",
                          fullWidth: 400,
                          fullHeight: 400,
                          aspectRatio: undefined
                        }}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__cjmE
                          )}
                        >
                          {"Lorem Ipsum"}
                        </h3>
                      </PersonCard>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__s9HS)}
                    >
                      <PersonCard
                        className={classNames(
                          "__wab_instance",
                          sty.personCard__os89X
                        )}
                        image={{
                          src: "/plasmic/agency_website/images/unnamedJpg.jpg",
                          fullWidth: 370,
                          fullHeight: 411,
                          aspectRatio: undefined
                        }}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__bAP8
                          )}
                        >
                          {"Lorem Ipsum"}
                        </h3>
                      </PersonCard>
                    </div>
                  </Stack__>
                </div>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__c3IMy)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__jq34B)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__ziY9E)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__c7UQu)}
                >
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__jfCna
                    )}
                  >
                    {"Our values"}
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___2DMeR
                    )}
                  >
                    {
                      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,"
                    }
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__cCw7L)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"serviceRow"}
                    data-plasmic-override={overrides.serviceRow}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.serviceRow)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__ryfz4)}
                    >
                      <ServiceValue
                        className={classNames(
                          "__wab_instance",
                          sty.serviceValue___42Vxs
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__dkeE8
                          )}
                        >
                          {"Value"}
                        </h3>
                      </ServiceValue>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__ifad7)}
                    >
                      <ServiceValue
                        className={classNames(
                          "__wab_instance",
                          sty.serviceValue__zpIvc
                        )}
                        slot={
                          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,"
                        }
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__nh7Ed
                          )}
                        >
                          {"Service"}
                        </h3>
                      </ServiceValue>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__gZBC)}
                    >
                      <ServiceValue
                        className={classNames(
                          "__wab_instance",
                          sty.serviceValue__ycbVp
                        )}
                        slot={
                          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,"
                        }
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3___3JqKy
                          )}
                        >
                          {"Value"}
                        </h3>
                      </ServiceValue>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__o3C4S)}
                    >
                      <ServiceValue
                        className={classNames(
                          "__wab_instance",
                          sty.serviceValue__zdQ39
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__cjxM0
                          )}
                        >
                          {"Value"}
                        </h3>
                      </ServiceValue>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column___8Hoal)}
                    >
                      <ServiceValue
                        className={classNames(
                          "__wab_instance",
                          sty.serviceValue__cjuh3
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__zz4A
                          )}
                        >
                          {"Value"}
                        </h3>
                      </ServiceValue>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column___0HFp)}
                    >
                      <ServiceValue
                        className={classNames(
                          "__wab_instance",
                          sty.serviceValue__s6L3K
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3__kuYEe
                          )}
                        >
                          {"Value"}
                        </h3>
                      </ServiceValue>
                    </div>
                  </Stack__>
                </Stack__>
              </Stack__>
            </Stack__>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__uBeO)}>
            <HomeFooterTop
              data-plasmic-name={"homeFooterTop"}
              data-plasmic-override={overrides.homeFooterTop}
              className={classNames("__wab_instance", sty.homeFooterTop)}
            />
          </div>
          <FooterMain
            data-plasmic-name={"footerMain"}
            data-plasmic-override={overrides.footerMain}
            className={classNames("__wab_instance", sty.footerMain)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "aboutUsBanner",
    "foreground2",
    "h1",
    "ourTeamSection",
    "columns",
    "container",
    "row1",
    "serviceRow",
    "homeFooterTop",
    "footerMain"
  ],

  header: ["header"],
  aboutUsBanner: ["aboutUsBanner", "foreground2", "h1"],
  foreground2: ["foreground2", "h1"],
  h1: ["h1"],
  ourTeamSection: ["ourTeamSection", "columns", "container", "row1"],
  columns: ["columns", "container", "row1"],
  container: ["container", "row1"],
  row1: ["row1"],
  serviceRow: ["serviceRow"],
  homeFooterTop: ["homeFooterTop"],
  footerMain: ["footerMain"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicAboutUs__ArgProps,
          internalVariantPropNames: PlasmicAboutUs__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAboutUs__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAboutUs";
  } else {
    func.displayName = `PlasmicAboutUs.${nodeName}`;
  }
  return func;
}

export const PlasmicAboutUs = Object.assign(
  // Top-level PlasmicAboutUs renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    aboutUsBanner: makeNodeComponent("aboutUsBanner"),
    foreground2: makeNodeComponent("foreground2"),
    h1: makeNodeComponent("h1"),
    ourTeamSection: makeNodeComponent("ourTeamSection"),
    columns: makeNodeComponent("columns"),
    container: makeNodeComponent("container"),
    row1: makeNodeComponent("row1"),
    serviceRow: makeNodeComponent("serviceRow"),
    homeFooterTop: makeNodeComponent("homeFooterTop"),
    footerMain: makeNodeComponent("footerMain"),
    // Metadata about props expected for PlasmicAboutUs
    internalVariantProps: PlasmicAboutUs__VariantProps,
    internalArgProps: PlasmicAboutUs__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "About Us",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicAboutUs;
/* prettier-ignore-end */
